// Generated by CoffeeScript 1.4.0
(function() {

  App.Chart = (function() {
    var getAnchors, height, paper, renderPath, renderPoint, width;

    function Chart() {}

    paper = void 0;

    getAnchors = function(p1x, p1y, p2x, p2y, p3x, p3y) {
      var a, alpha, b, dx1, dx2, dy1, dy2, l1, l2;
      l1 = (p2x - p1x) / 2;
      l2 = (p3x - p2x) / 2;
      a = Math.atan((p2x - p1x) / Math.abs(p2y - p1y));
      b = Math.atan((p3x - p2x) / Math.abs(p2y - p3y));
      if (p1y < p2y) {
        a = Math.PI - a;
      }
      if (p3y < p2y) {
        b = Math.PI - b;
      }
      alpha = Math.PI / 2 - ((a + b) % (Math.PI * 2)) / 2;
      dx1 = l1 * Math.sin(alpha + a);
      dy1 = l1 * Math.cos(alpha + a);
      dx2 = l2 * Math.sin(alpha + b);
      dy2 = l2 * Math.cos(alpha + b);
      return {
        x1: p2x - dx1,
        y1: p2y + dy1,
        x2: p2x + dx2,
        y2: p2y + dy2
      };
    };

    renderPath = function() {
      var X, X0, X2, Y, Y0, Y2, a, i, max, p, path, x, y, _i, _ref;
      X = width() / App.Model.length;
      max = Math.max.apply(Math, App.Model);
      Y = height() / max;
      path = paper.path().attr({
        stroke: "#009874",
        "stroke-width": 4,
        "stroke-linejoin": "round"
      });
      for (i = _i = 0, _ref = App.Model.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        y = Math.round(height() - Y * App.Model[i]);
        x = Math.round(X * (i + .5));
        if (i === 0) {
          p = ["M", x, y, "C", x, y];
        }
        if (i !== 0 && i < App.Model.length - 1) {
          Y0 = Math.round(height() - Y * App.Model[i - 1]);
          X0 = Math.round(X * (i - .5));
          Y2 = Math.round(height() - Y * App.Model[i + 1]);
          X2 = Math.round(X * (i + 1.5));
          a = getAnchors(X0, Y0, x, y, X2, Y2);
          console.log(a);
          p = p.concat([a.x1, a.y1, x, y, a.x2, a.y2]);
        }
      }
      p = p.concat([x, y, x, y]);
      return path.attr({
        path: p
      });
    };

    renderPoint = function(x, y) {};

    height = function() {
      return innerHeight - 70;
    };

    width = function() {
      return $('#chart').innerWidth();
    };

    Chart.prototype.render = function() {
      if (paper) {
        paper.remove();
      }
      paper = new Raphael('chart', width(), height());
      return renderPath();
    };

    return Chart;

  })();

}).call(this);
